### ISSUE TITLE
[ BUG ] defaults to 4 per line after a video randomly

### ISSUE THREAD

**Issue by Demon1986** [RootOperator/Youtube-row-fixer#12]
**Describe the bug**
after watching a video, and clicking the youtube icon (on the top left), the page defaults back to 4 per line, instead of what it's set to (7 in my case)

**To Reproduce**
1. Go to a video
2. Watch till the end
3. Click the youtube icon

**Expected behavior**
that would be whatever # of thumbnails you have set it to.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Screen resolution: 1920x1080
 - Version: 2.3.3

**Additional context**
![yt_row](https://user-images.githubusercontent.com/5293267/124640218-67e8d800-de8d-11eb-8718-fa626e75f646.png)

**Comment by RootOperator** [comment]
Thanks for creating this issue. we know this bug exists and we are working to fix it, but due to us not being able to reliably reproduce the bug every time it will take some time for us to make sure the bug is fixed.

**Comment by Demon1986** [comment]
i can replicate it pretty easy. you watch the video to the end, and immediatly hit the icon, if you wait (like reading comments) it seems to work, but who wants to wait all the time?

if you're still unable to replicate it, tell me how i can help you with it

**Comment by RootOperator** [comment]
it should be fixed now. make sure to update the extension to version 2.3.4

for information on how to update the extension click [here](https://support.mozilla.org/en-US/kb/how-update-add-ons)
