### ISSUE TITLE
[ BUG ] resizing issue

### ISSUE THREAD

**Issue by L27SlubbyGames** [RootOperator/Youtube-row-fixer#2]
**Describe the bug**
When you make your browser smaller and then go back to fullscreen, the thumbnails are back to normal.

**To Reproduce**
1. Set slider on 8
2. Make browser smaller
3. Make the browser fullscreen
4. Thumbnail default size

**Expected behavior**
That the thumbnail must be the size I have indicated.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit version: 10.0.18362 Build 18362
 - Browser: Firefox
 - Version:  70.0.1

**Comment by RootOperator** [comment]
this bug has been resolved with #3
