### ISSUE TITLE
after clicking the "youtube" link, after watching a vid, gets one video per line.

### ISSUE THREAD

**Issue by Demon1986** [RootOperator/Youtube-row-fixer#9]
**Describe the bug**
after watching a video, the extension turns into 1 line with icons, rather than what's preset, only workaround is to refresh (F5)

**To Reproduce**
1. Go to a video and watch it (might not work if you don't watch it full screen to end)
2. Click on the YouTube icon on the top left of the screen
3. 1 video per line, rather than your settings (icons appear too if you have them off)

**Expected behavior**
should be respecting the settings regardless of what you do

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox

**Smartphone (please complete the following information):**
 - Version 73.0.1

**Additional context**
might only happen with the Danish version, not sure.

![rowfixerrror](https://user-images.githubusercontent.com/5293267/75977826-7ca20e00-5edd-11ea-8a3a-cc1eda96f5d2.JPG)

**Comment by RootOperator** [comment]
Thank you for reporting this bug, we will be fixing this as soon as possible.

**Comment by RootOperator** [comment]
the new version should come live today, so remember to update the extension

**Comment by Demon1986** [comment]
not fixed, still doing it, sometimes it'll reset it to standard (4 with icons) while i have it to 7 without any icons at all
